In [1]:
import pandas as pd
import numpy as np
import collections
import matplotlib.pyplot as plt

In [2]:
train = pd.read_json ('train.json', lines=True)

In [3]:
train.head(5)

index            id                                           sequence  \
0      0  id_001f94081  GGAAAAGCUCUAAUAACAGGAGACUAGGACUACGUAUUUCUAGGUA...   
1      1  id_0049f53ba  GGAAAAAGCGCGCGCGGUUAGCGCGCGCUUUUGCGCGCGCUGUACC...   
2      2  id_006f36f57  GGAAAGUGCUCAGAUAAGCUAAGCUCGAAUAGCAAUCGAAUAGAAU...   
3      3  id_0082d463b  GGAAAAGCGCGCGCGCGCGCGCGAAAAAGCGCGCGCGCGCGCGCGC...   
4      4  id_0087940f4  GGAAAAUAUAUAAUAUAUUAUAUAAAUAUAUUAUAGAAGUAUAAUA...   

                                           structure  \
0  .....((((((.......)))).)).((.....((..((((((......   
1  .....(((((((((((((((((((((((....)))))))))).)))...   
2  .....((((.((.....((((.(((.....)))..((((......)...   
3  ......((((((((((((((((......))))))))))))))))((...   
4  .....(((((((.((((((((((((.(((((((((....)))))))...   

                                 predicted_loop_type  signal_to_noise  \
0  EEEEESSSSSSHHHHHHHSSSSBSSXSSIIIIISSIISSSSSSHHH...            6.894   
1  EEEEESSSSSSSSSSSSSSSSSSSSSSSHHHHSSSSSSSSSSBSSS...            0.193   
2  EEEEESSSSISSIIIIISSSSMSSSHHHHHSSSMMSSSSHHHHHHS...            8.800   
3  EEEEEESSSSSSSSSSSSSSSSHHHHHHSSSSSSSSSSSSSSSSSS...            0.104   
4  EEEEESSSSSSSBSSSSSSSSSSSSBSSSSSSSSSHHHHSSSSSSS...            0.423   

   SN_filter  seq_length  seq_scored  \
0          1         107          68   
1          0         107          68   
2          1         107          68   
3          0         107          68   
4          0         107          68   

                                    reactivity_error  \
0  [0.1359, 0.20700000000000002, 0.1633, 0.1452, ...   
1  [2.8272, 2.8272, 2.8272, 4.7343, 2.5676, 2.567...   
2  [0.0931, 0.13290000000000002, 0.11280000000000...   
3  [3.5229, 6.0748, 3.0374, 3.0374, 3.0374, 3.037...   
4  [1.665, 2.1728, 2.0041, 1.2405, 0.620200000000...   

                                   deg_error_Mg_pH10  \
0  [0.26130000000000003, 0.38420000000000004, 0.1...   
1  [73705.3985, 73705.3985, 73705.3985, 73705.398...   
2  [0.1365, 0.2237, 0.1812, 0.1333, 0.1148, 0.160...   
3  [73705.3985, 73705.3985, 73705.3985, 73705.398...   
4  [4.2139, 3.9637000000000002, 3.2467, 2.4716, 1...   

                                      deg_error_pH10  \
0  [0.2631, 0.28600000000000003, 0.0964, 0.1574, ...   
1  [10.1986, 9.2418, 5.0933, 5.0933, 5.0933, 5.09...   
2  [0.17020000000000002, 0.178, 0.111, 0.091, 0.0...   
3  [11.8007, 12.7566, 5.7733, 5.7733, 5.7733, 5.7...   
4  [3.0942, 3.015, 2.1212, 2.0552, 0.881500000000...   

                                    deg_error_Mg_50C  \
0  [0.1501, 0.275, 0.0947, 0.18660000000000002, 0...   
1  [16.6174, 13.868, 8.1968, 8.1968, 8.1968, 8.19...   
2  [0.1033, 0.1464, 0.1126, 0.09620000000000001, ...   
3  [121286.7181, 121286.7182, 121286.7181, 121286...   
4  [2.6717, 2.4818, 1.9919, 2.5484999999999998, 1...   

                                       deg_error_50C  \
0  [0.2167, 0.34750000000000003, 0.188, 0.2124, 0...   
1  [15.4857, 7.9596, 13.3957, 5.8777, 5.8777, 5.8...   
2  [0.14980000000000002, 0.1761, 0.1517, 0.116700...   
3  [15.3995, 8.1124, 7.7824, 7.7824, 7.7824, 7.78...   
4  [1.3285, 3.6173, 1.3057, 1.3021, 1.1507, 1.150...   

                                          reactivity  \
0  [0.3297, 1.5693000000000001, 1.1227, 0.8686, 0...   
1  [0.0, 0.0, 0.0, 2.2965, 0.0, 0.0, 0.0, 0.0, 0....   
2  [0.44820000000000004, 1.4822, 1.1819, 0.743400...   
3  [0.0, 2.2399, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0....   
4  [0.8267, 2.6577, 2.8481, 0.40090000000000003, ...   

                                         deg_Mg_pH10  \
0  [0.7556, 2.983, 0.2526, 1.3789, 0.637600000000...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.2504, 1.4021, 0.9804, 0.49670000000000003, ...   
3  [0.0, -0.5083, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...   
4  [2.1058, 3.138, 2.5437000000000003, 1.0932, 0....   

                                            deg_pH10  \
0  [2.3375, 3.5060000000000002, 0.3008, 1.0108, 0...   
1  [4.947, 4.4523, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [4]:
def prop_base(x):
    v = np.array(list(x))
    prop_A = np.mean(v == 'A')
    prop_C = np.mean(v == 'C')
    prop_U = np.mean(v == 'U')
    return prop_A, prop_C, prop_U

In [5]:
def prop_loop_type(x):
    v = np.array(list(x))
    prop_S = np.mean(v == 'S')
    prop_E = np.mean(v == 'E')
    prop_H = np.mean(v == 'H')
    prop_B = np.mean(v == 'B')
    prop_I = np.mean(v == 'I')
    prop_X = np.mean(v == 'X')
    return prop_S,prop_E,prop_H,prop_B,prop_I,prop_X

In [6]:
prop_base(train['sequence'].values[0])

(0.4205607476635514, 0.21495327102803738, 0.18691588785046728)

In [7]:
prop_loop_type(train['predicted_loop_type'].values[0])

(0.42990654205607476,
 0.24299065420560748,
 0.14018691588785046,
 0.009345794392523364,
 0.1308411214953271,
 0.04672897196261682)

In [8]:
train_data = []
for mol_id in train['id'].unique():
    sample_data = train.loc[train['id'] == mol_id]
    pA, pC, pU = prop_base(sample_data['sequence'].values[0])
    pS, pE, pH, pB, pI, pX = prop_loop_type(sample_data['predicted_loop_type'].values[0])
    for i in range(68):
        sample_tuple = (sample_data['id'].values[0]+'_'+str(i), sample_data['sequence'].values[0][i],
                        pA,pC,pU,
                        sample_data['structure'].values[0][i], sample_data['predicted_loop_type'].values[0][i],
                        pS,pE,pH,pB,pI,pX,
                        sample_data['reactivity'].values[0][i], 
                        sample_data['deg_Mg_pH10'].values[0][i],
                        sample_data['deg_pH10'].values[0][i],
                        sample_data['deg_Mg_50C'].values[0][i],
                        sample_data['deg_50C'].values[0][i])
        train_data.append(sample_tuple)
    for i in range(68,107):
        sample_tuple = (sample_data['id'].values[0]+'_'+str(i), sample_data['sequence'].values[0][i],pA,pC,pU,
                        sample_data['structure'].values[0][i], sample_data['predicted_loop_type'].values[0][i],
                        pS,pE,pH,pB,pI,pX,
                        0, 
                        0,
                        0,
                        0,
                        0)
        train_data.append(sample_tuple)

In [9]:
train_data = pd.DataFrame(train_data, columns=['id', 'sequence','prop_base_A','prop_base_C','prop_base_U', 'structure', 'predicted_loop_type',
                                               'prop_loop_S','prop_loop_E','prop_loop_H','prop_loop_B','prop_loop_I','prop_loop_X','reactivity', 'deg_Mg_pH10',
                                  'deg_pH10', 'deg_Mg_50C', 'deg_50C'])

In [10]:
train_data.head(10)

id sequence  prop_base_A  prop_base_C  prop_base_U structure  \
0  id_001f94081_0        G     0.420561     0.214953     0.186916         .   
1  id_001f94081_1        G     0.420561     0.214953     0.186916         .   
2  id_001f94081_2        A     0.420561     0.214953     0.186916         .   
3  id_001f94081_3        A     0.420561     0.214953     0.186916         .   
4  id_001f94081_4        A     0.420561     0.214953     0.186916         .   
5  id_001f94081_5        A     0.420561     0.214953     0.186916         (   
6  id_001f94081_6        G     0.420561     0.214953     0.186916         (   
7  id_001f94081_7        C     0.420561     0.214953     0.186916         (   
8  id_001f94081_8        U     0.420561     0.214953     0.186916         (   
9  id_001f94081_9        C     0.420561     0.214953     0.186916         (   

  predicted_loop_type  prop_loop_S  prop_loop_E  prop_loop_H  prop_loop_B  \
0                   E     0.429907     0.242991     0.140187     0.009346   
1                   E     0.429907     0.242991     0.140187     0.009346   
2                   E     0.429907     0.242991     0.140187     0.009346   
3                   E     0.429907     0.242991     0.140187     0.009346   
4                   E     0.429907     0.242991     0.140187     0.009346   
5                   S     0.429907     0.242991     0.140187     0.009346   
6                   S     0.429907     0.242991     0.140187     0.009346   
7                   S     0.429907     0.242991     0.140187     0.009346   
8                   S     0.429907     0.242991     0.140187     0.009346   
9                   S     0.429907     0.242991     0.140187     0.009346   

   prop_loop_I  prop_loop_X  reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C  \
0     0.130841     0.046729      0.3297       0.7556    2.3375      0.3581   
1     0.130841     0.046729      1.5693       2.9830    3.5060      2.9683   
2     0.130841     0.046729      1.1227       0.2526    0.3008      0.2589   
3     0.130841     0.046729      0.8686       1.3789    1.0108      1.4552   
4     0.130841     0.046729      0.7217       0.6376    0.2635      0.7244   
5     0.130841     0.046729      0.4384       0.3313    0.3403      0.4971   
6     0.130841     0.046729      0.2560       0.6763    0.5617      0.3819   
7     0.130841     0.046729      0.3364       0.7525    0.6810      0.9115   
8     0.130841     0.046729      0.2168       0.2080    0.0530      0.1668   
9     0.130841     0.046729      0.3583       0.8908    0.5348      1.0613   

   deg_50C  
0   0.6382  
1   3.4773  
2   0.9988  
3   1.3228  
4   0.7877  
5   0.5890  
6   0.5231  
7   1.0125  
8   0.0585  
9   0.7349

In [11]:
train_data.head(108)

id sequence  prop_base_A  prop_base_C  prop_base_U  \
0      id_001f94081_0        G     0.420561     0.214953     0.186916   
1      id_001f94081_1        G     0.420561     0.214953     0.186916   
2      id_001f94081_2        A     0.420561     0.214953     0.186916   
3      id_001f94081_3        A     0.420561     0.214953     0.186916   
4      id_001f94081_4        A     0.420561     0.214953     0.186916   
..                ...      ...          ...          ...          ...   
103  id_001f94081_103        C     0.420561     0.214953     0.186916   
104  id_001f94081_104        A     0.420561     0.214953     0.186916   
105  id_001f94081_105        A     0.420561     0.214953     0.186916   
106  id_001f94081_106        C     0.420561     0.214953     0.186916   
107    id_0049f53ba_0        G     0.233645     0.299065     0.158879   

    structure predicted_loop_type  prop_loop_S  prop_loop_E  prop_loop_H  \
0           .                   E     0.429907     0.242991     0.140187   
1           .                   E     0.429907     0.242991     0.140187   
2           .                   E     0.429907     0.242991     0.140187   
3           .                   E     0.429907     0.242991     0.140187   
4           .                   E     0.429907     0.242991     0.140187   
..        ...                 ...          ...          ...          ...   
103         .                   E     0.429907     0.242991     0.140187   
104         .                   E     0.429907     0.242991     0.140187   
105         .                   E     0.429907     0.242991     0.140187   
106         .                   E     0.429907     0.242991     0.140187   
107         .                   E     0.616822     0.242991     0.102804   

     prop_loop_B  prop_loop_I  prop_loop_X  reactivity  deg_Mg_pH10  deg_pH10  \
0       0.009346     0.130841     0.046729      0.3297       0.7556    2.3375   
1       0.009346     0.130841     0.046729      1.5693       2.9830    3.5060   
2       0.009346     0.130841     0.046729      1.1227       0.2526    0.3008   
3       0.009346     0.130841     0.046729      0.8686       1.3789    1.0108   
4       0.009346     0.130841     0.046729      0.7217       0.6376    0.2635   
..           ...          ...          ...         ...          ...       ...   
103     0.009346     0.130841     0.046729      0.0000       0.0000    0.0000   
104     0.009346     0.130841     0.046729      0.0000       0.0000    0.0000   
105     0.009346     0.130841     0.046729      0.0000       0.0000    0.0000   
106     0.009346     0.130841     0.046729      0.0000       0.0000    0.0000   
107     0.009346     0.000000     0.000000      0.0000       0.0000    4.9470   

     deg_Mg_50C  deg_50C  
0        0.3581   0.6382  
1        2.9683   3.4773  
2        0.2589   0.9988  
3        1.4552   1.3228  
4        0.7244   0.7877  
..          ...      ...  
103      0.0000   0.0000  
104      0.0000   0.0000  
105      0.0000   0.0000  
106      0.0000   0.0000  
107      4.8511   7.6692  

[108 rows x 18 columns]

In [12]:
dummies_base = pd.get_dummies(train_data['sequence'])
dummies_loop = pd.get_dummies(train_data['predicted_loop_type'])
dummies_struct = pd.get_dummies(train_data['structure'])

In [13]:
dummies_base.head()

A  C  G  U
0  0  0  1  0
1  0  0  1  0
2  1  0  0  0
3  1  0  0  0
4  1  0  0  0

In [14]:
dummies_loop.head()

B  E  H  I  M  S  X
0  0  1  0  0  0  0  0
1  0  1  0  0  0  0  0
2  0  1  0  0  0  0  0
3  0  1  0  0  0  0  0
4  0  1  0  0  0  0  0

In [15]:
dummies_struct.head()

(  )  .
0  0  0  1
1  0  0  1
2  0  0  1
3  0  0  1
4  0  0  1

In [16]:
df = train_data.drop(["sequence", "predicted_loop_type","structure"], axis = 1)

In [17]:
df = pd.concat([df,dummies_base,dummies_loop,dummies_struct], axis = 1)

In [18]:
df.head()

id  prop_base_A  prop_base_C  prop_base_U  prop_loop_S  \
0  id_001f94081_0     0.420561     0.214953     0.186916     0.429907   
1  id_001f94081_1     0.420561     0.214953     0.186916     0.429907   
2  id_001f94081_2     0.420561     0.214953     0.186916     0.429907   
3  id_001f94081_3     0.420561     0.214953     0.186916     0.429907   
4  id_001f94081_4     0.420561     0.214953     0.186916     0.429907   

   prop_loop_E  prop_loop_H  prop_loop_B  prop_loop_I  prop_loop_X  ...  B  E  \
0     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  1   
1     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  1   
2     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  1   
3     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  1   
4     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  1   

   H  I  M  S  X  (  )  .  
0  0  0  0  0  0  0  0  1  
1  0  0  0  0  0  0  0  1  
2  0  0  0  0  0  0  0  1  
3  0  0  0  0  0  0  0  1  
4  0  0  0  0  0  0  0  1  

[5 rows x 29 columns]

## séparation X et Y

In [19]:
X = df.loc[:,["id","prop_base_A","prop_base_C","prop_base_U",
             "prop_loop_S","prop_loop_E","prop_loop_H","prop_loop_B","prop_loop_I","prop_loop_X",
             "A","C","G","U","(",")",".","B","E","H","I","M","S","X"]]

In [20]:
X.head()

id  prop_base_A  prop_base_C  prop_base_U  prop_loop_S  \
0  id_001f94081_0     0.420561     0.214953     0.186916     0.429907   
1  id_001f94081_1     0.420561     0.214953     0.186916     0.429907   
2  id_001f94081_2     0.420561     0.214953     0.186916     0.429907   
3  id_001f94081_3     0.420561     0.214953     0.186916     0.429907   
4  id_001f94081_4     0.420561     0.214953     0.186916     0.429907   

   prop_loop_E  prop_loop_H  prop_loop_B  prop_loop_I  prop_loop_X  ...  (  )  \
0     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  0   
1     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  0   
2     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  0   
3     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  0   
4     0.242991     0.140187     0.009346     0.130841     0.046729  ...  0  0   

   .  B  E  H  I  M  S  X  
0  1  0  1  0  0  0  0  0  
1  1  0  1  0  0  0  0  0  
2  1  0  1  0  0  0  0  0  
3  1  0  1  0  0  0  0  0  
4  1  0  1  0  0  0  0  0  

[5 rows x 24 columns]

In [21]:
Y = df.loc[:,["reactivity","deg_Mg_pH10","deg_pH10","deg_Mg_50C","deg_50C"]]

In [22]:
Y.head()

reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C  deg_50C
0      0.3297       0.7556    2.3375      0.3581   0.6382
1      1.5693       2.9830    3.5060      2.9683   3.4773
2      1.1227       0.2526    0.3008      0.2589   0.9988
3      0.8686       1.3789    1.0108      1.4552   1.3228
4      0.7217       0.6376    0.2635      0.7244   0.7877

## Creation train et test

In [24]:
nb_mol = X.shape[0]//107

In [25]:
liste_ind = np.arange(0,nb_mol)

In [26]:
liste_ind

array([   0,    1,    2, ..., 2397, 2398, 2399])

In [27]:
ind_train = np.random.choice(liste_ind,size = int(0.8*nb_mol), replace = False)

In [33]:
ind_train
ind_test = liste_ind[-ind_train]

In [34]:
print(ind_train)
print(ind_test)

[2179 2154 1778 ... 2343  666  943]
[ 221  246  622 ...   57 1734 1457]


In [35]:
indice_train = np.array([])
for i in ind_train:
    liste_indice = np.arange(i*107,i*107+107)
    indice_train = np.append(indice_train,liste_indice)

In [36]:
indice_test = np.array([])
for i in ind_test:
    liste_indice = np.arange(i*107,i*107+107)
    indice_test = np.append(indice_test,liste_indice)

In [37]:
X_train = X.loc[indice_train,:]
Y_train = Y.loc[indice_train,:]

In [38]:
X_test = X.loc[indice_test,:]
Y_test = Y.loc[indice_test,:]

In [39]:
Y_train

reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C  deg_50C
233153.0      0.0000       0.0000    0.0000      0.0000   0.0000
233154.0      0.0000       0.0000    0.0000      0.0000   0.0000
233155.0      0.0000       0.0000    0.0000      0.0000   0.0000
233156.0      0.0000      14.7293   44.4886      0.0000   0.0000
233157.0     -0.0008      -1.6388   -1.1041     -0.0013  -0.0009
...              ...          ...       ...         ...      ...
101003.0      0.0000       0.0000    0.0000      0.0000   0.0000
101004.0      0.0000       0.0000    0.0000      0.0000   0.0000
101005.0      0.0000       0.0000    0.0000      0.0000   0.0000
101006.0      0.0000       0.0000    0.0000      0.0000   0.0000
101007.0      0.0000       0.0000    0.0000      0.0000   0.0000

[205440 rows x 5 columns]

In [40]:
Y_test

reactivity  deg_Mg_pH10  deg_pH10  deg_Mg_50C  deg_50C
23647.0       0.7010       0.7016    2.4817      0.3485   0.5827
23648.0       1.6265       2.2608    2.9635      1.4410   1.4916
23649.0       1.5213       1.4799    1.3039      1.1209   1.1886
23650.0       1.4475       0.7443    0.7082      0.7304   0.7556
23651.0       0.5279       0.3851    0.5295      0.4037   0.5696
...              ...          ...       ...         ...      ...
156001.0      0.0000       0.0000    0.0000      0.0000   0.0000
156002.0      0.0000       0.0000    0.0000      0.0000   0.0000
156003.0      0.0000       0.0000    0.0000      0.0000   0.0000
156004.0      0.0000       0.0000    0.0000      0.0000   0.0000
156005.0      0.0000       0.0000    0.0000      0.0000   0.0000

[205440 rows x 5 columns]

## Régression linéaire

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
reg = LinearRegression()

In [44]:
reg.fit(X_train.loc[:,["prop_base_A","prop_base_C","prop_base_U",
             "prop_loop_S","prop_loop_E","prop_loop_H","prop_loop_B","prop_loop_I","prop_loop_X",
             "A","C","G","U","(",")",".","B","E","H","I","M","S","X"]],Y_train)

LinearRegression()

In [46]:
y_pred = reg.predict(X_test.loc[:,["prop_base_A","prop_base_C","prop_base_U",
             "prop_loop_S","prop_loop_E","prop_loop_H","prop_loop_B","prop_loop_I","prop_loop_X",
             "A","C","G","U","(",")",".","B","E","H","I","M","S","X"]])

In [47]:
y_pred

array([[0.322258  , 0.41912842, 0.6031189 , 0.37962341, 0.37426758],
       [0.322258  , 0.41912842, 0.6031189 , 0.37962341, 0.37426758],
       [0.27466583, 0.25286865, 0.3187561 , 0.28977966, 0.2590332 ],
       ...,
       [0.28487396, 0.25372314, 0.32653809, 0.28077698, 0.28137207],
       [0.28487396, 0.25372314, 0.32653809, 0.28077698, 0.28137207],
       [0.13895416, 0.22271729, 0.35302734, 0.21360779, 0.22912598]])

In [58]:
import sklearn.metrics

In [63]:
def mcrmse(y_true, y_pred):
    colwise_mse = np.mean((y_true-y_pred)**2, axis = 1)
    return np.mean(np.sqrt(colwise_mse))

In [64]:
y_true = Y_test.to_numpy()

In [65]:
y_true

array([[0.701 , 0.7016, 2.4817, 0.3485, 0.5827],
       [1.6265, 2.2608, 2.9635, 1.441 , 1.4916],
       [1.5213, 1.4799, 1.3039, 1.1209, 1.1886],
       ...,
       [0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    ]])

In [66]:
y_pred.shape

(205440, 5)

In [67]:
y_true.shape

(205440, 5)

In [69]:
mcrmse(y_true,y_pred)

0.3490777905689182